version: '3.7'

services:

  php-fpm:
    build: php
    container_name: 'php'
    ports:
      - '9000:9000'
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      - SYMFONY_VERSION=7.0.4

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - '8000:80'
    volumes:
      - ../:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # postgres:
  #   image: postgres:15
  #   ports:
  #     - 15432:5432
  #   container_name: 'postgresql'
  #   working_dir: /app
  #   restart: always
  #   environment:
  #     POSTGRES_DB: 'db'
  #     POSTGRES_USER: 'user'
  #     POSTGRES_PASSWORD: 'password'
  #   volumes:
  #     - dump:/app/dump
  #     - postgresql:/var/lib/postgresql/data

volumes:
  dump:
  postgresql: