controllers:
    resource:
        path: ../src/Shared/Infrastructure/Controller/
        namespace: App\Shared\Infrastructure\Controller
#        namespace: App\Controller

    type: attribute

kernel:
    resource: ../src/Shared/Infrastructure/Kernel.php
    type: attribute

#api_refresh_token:
#    path: /api/auth/token/refresh

api_login_check:
    path: /api/auth/token/login

#api_login_check:
#    path: /api/login_check

users:
    resource: ../src/Users/Infrastructure/Controller/
    type: attribute